### ISSUE TITLE
Cannot create a Text assets.

### ISSUE THREAD

**Issue by pdukaf** [Opteo/google-ads-api#105]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [X ] question about how to use this project

### Summary
I am trying to create a text asset using `customer.assets.create(..)`  and receiving following error.

my sample object is:
```
{
 type: 5,      
  text_asset: { text: "Some sample descriptions' },
  name: 'Ad group as id' 
}
// Error: The Asset.asset_data oneof is empty.
```

Is there anything I am missing ? 

```
{ Error: The Asset.asset_data oneof is empty.
    at AdGroupAdService.<anonymous> (/home/umesh/dev/alkomo/node_modules/google-ads-api/build/services/service.js:178:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/umesh/dev/alkomo/node_modules/google-ads-api/build/services/service.js:6:65)
    at /home/umesh/.meteor/packages/promise/.0.11.2.1nfm0ms.xv6b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
  code: { assetError: 5 },
  request: { customerId: '42786198986', operationsList: [ [Object] ] },
  request_id: '9Ii5c_txqcnCCLTtSEvJqw',
  location: 'operations[0]',
  failure: 
   { Error: 3 INVALID_ARGUMENT: The Asset.asset_data oneof is empty.
    at Object.exports.createStatusError (/home/umesh/dev/alkomo/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/umesh/dev/alkomo/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/umesh/dev/alkomo/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/umesh/dev/alkomo/node_modules/grpc/src/client_interceptors.js:618:8)
    at Object.grpc_1.default.ListenerBuilder.withOnReceiveStatus [as onReceiveStatus] (/home/umesh/dev/alkomo/node_modules/google-ads-node/build/lib/interceptor.js:108:17)
    at InterceptingListener._callNext (/home/umesh/dev/alkomo/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/umesh/dev/alkomo/node_modules/grpc/src/client_interceptors.js:618:8)
    at Object.grpc_1.default.ListenerBuilder.withOnReceiveStatus [as onReceiveStatus] (/home/umesh/dev/alkomo/node_modules/google-ads-node/build/lib/interceptor.js:160:13)
    at InterceptingListener._callNext (/home/umesh/dev/alkomo/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/umesh/dev/alkomo/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/umesh/dev/alkomo/node_modules/grpc/src/client_interceptors.js:847:24)
     code: 3,
     metadata: Metadata { _internal_repr: [Object], flags: 0 },
     details: 'The Asset.asset_data oneof is empty.' } } Promise { <pending> }
```

**Comment by kritzware** [comment]
Hi @pdukaf, does it work if you put the `text_asset` object inside `asset_data`? 
```javascript
{
  type: 5,
  asset_data: {
    text_asset: { ... },
  },
  name: 'asset',
}
```

**Comment by pdukaf** [comment]
I still getting this error while creating TEXT ASSETS. 

Is it a bug ? Its urgent can anyone help ?

```
{ type: 5,      
  asset_data: { text_asset: { text: 'Hello Umesh How are you' } },
  name: 'asset' }
#####################################
Error: Attempted to set value "Hello Umesh How are you" on invalid path "asset_data.text_asset.text" in resource
    at toProtoValueFormat (/home/umesh/dev/alkomo/node_modules/google-ads-node/build/lib/utils.js:99:15)
    at unroll (/home/umesh/dev/alkomo/node_modules/google-ads-node/build/lib/utils.js:90:19)
    at convertToProtoFormat (/home/umesh/dev/alkomo/node_modules/google-ads-node/build/lib/utils.js:86:26)
    at unroll (/home/umesh/dev/alkomo/node_modules/google-ads-node/build/lib/utils.js:89:19)
    at convertToProtoFormat (/home/umesh/dev/alkomo/node_modules/google-ads-node/build/lib/utils.js:86:26)
    at unroll (/home/umesh/dev/alkomo/node_modules/google-ads-node/build/lib/utils.js:89:19)
    at Object.convertToProtoFormat (/home/umesh/dev/alkomo/node_modules/google-ads-node/build/lib/utils.js:86:26)
    at GoogleAdsClient.buildResource (/home/umesh/dev/alkomo/node_modules/google-ads-node/build/lib/client.js:82:41
    at GrpcClient.buildResource (/home/umesh/dev/alkomo/node_modules/google-ads-api/build/grpc.js:111:28)
    at AdGroupAdService.buildResource (/home/umesh/dev/alkomo/node_modules/google-ads-api/build/services/service.js
    at AdGroupAdService.<anonymous> (/home/umesh/dev/alkomo/node_modules/google-ads-api/build/services/service.js:9
    at Generator.next (<anonymous>)
    at /home/umesh/dev/alkomo/node_modules/google-ads-api/build/services/service.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/umesh/dev/alkomo/node_modules/google-ads-api/build/services/service.js:4:12)
    at AdGroupAdService.serviceCreate (/home/umesh/dev/alkomo/node_modules/google-ads-api/build/services/service.js
    at AdGroupAdService.<anonymous> (/home/umesh/dev/alkomo/node_modules/google-ads-api/build/services/asset.js:45:
    at Generator.next (<anonymous>)
    at /home/umesh/dev/alkomo/node_modules/google-ads-api/build/services/asset.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (/home/umesh/dev/alkomo/node_modules/google-ads-api/build/services/asset.js:5:12)
    at AdGroupAdService.create (/home/umesh/dev/alkomo/node_modules/google-ads-api/build/services/asset.js:44:16)

```

**Comment by mhnpd** [comment]
I can confirm, I cannot create text assets. I have implemented it as per documentation. Is this a bug?

**Comment by zarinn3pal** [comment]
Anybody able to resolve this issue?

**Comment by WillCooter** [comment]
working on it this week

**Comment by WillCooter** [comment]
This is a part of the Google's API, text assets can not be created on their own - they must instead be "_created inline during ad creation_". Apologies, nothing we can do here. We will update our docs to explain this asap.

[Source](https://developers.google.com/google-ads/api/docs/assets/working-with-assets)
