### ISSUE TITLE
TypeError: Cannot read property 'googleads' of undefined

### ISSUE THREAD

**Issue by lotvall** [Opteo/google-ads-api#121]
### I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] question about the decisions made in the repository
  - [x] question about how to use this project
 

### Summary

I am getting an error when creating a campaign with `google-ads-api` and I am not sure what the problem is here. I've been following the callstack up to compiled-resources where the error seems to be but can't open this file.

Does anybody know what the issue might be? 

Is there a bug or am I doing something wrong?

I initally made an issue [here](https://github.com/Opteo/google-ads-node/issues/38), but I realize this repo is probably a better place.

This is what the code looks like:

```
const client = new GoogleAdsApi({
    client_id: process.env.ADWORDS_CLIENT_ID,
    client_secret: process.env.ADWORDS_SECRET,
    developer_token: process.env.ADWORDS_DEVELOPER_TOKEN
  });

  const customer = client.Customer({
    customer_account_id: clientAccountId,
    login_customer_id: process.env.ADWORDS_CUSTOMER_ID,
    refresh_token: process.env.ADWORDS_REFRESH_TOKEN
  });

 const { results  } = await customer.campaigns.create(
    campaignData
  );

```

### Other information
```
TypeError: Cannot read property 'googleads' of undefined
    at Function.Campaign.fromObject (/Users/alexanderlotvall/GoogleAdsService/node_modules/google-ads-node/build/protos/compiled-resources.js:1:2603399)
    at GoogleAdsClient.buildResource (/Users/alexanderlotvall/GoogleAdsService/node_modules/google-ads-node/build/lib/client.js:95:30)
    at GrpcClient.buildResource (/Users/alexanderlotvall/GoogleAdsService/node_modules/google-ads-api/build/grpc.js:121:28)
    at CampaignService.buildResource (/Users/alexanderlotvall/GoogleAdsService/node_modules/google-ads-api/build/services/service.js:228:32)
    at CampaignService.<anonymous> (/Users/alexanderlotvall/GoogleAdsService/node_modules/google-ads-api/build/services/service.js:110:33)
    at Generator.next (<anonymous>)
    at /Users/alexanderlotvall/GoogleAdsService/node_modules/google-ads-api/build/services/service.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/alexanderlotvall/GoogleAdsService/node_modules/google-ads-api/build/services/service.js:4:12)
    at CampaignService.serviceCreate (/Users/alexanderlotvall/GoogleAdsService/node_modules/google-ads-api/build/services/service.js:93:16)
```

**Comment by kritzware** [comment]
Could you share with us how the variable `campaignData` looks?
