### ISSUE TITLE
Cannot use customer.conversionActions.create() really would appreciate some help

### ISSUE THREAD

**Issue by Sotacan** [Opteo/google-ads-api#122]
### I'm submitting a ...

-   [X] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [X] question about how to use this project

### Summary

No matter what I do I can't get a `conversion_action` object accepted by `conversionActions.create()`

This is for a client and I would really appreciate some help, am willing to pay for some mentorship if need be, thanks!

I am trying to use this code:
`customer.conversionActions.create(conversion_action);`

I get this issue:
`Error: The required field was not present.`

Here is a photo of the `conversion_action` object I'm trying to use:
https://i.gyazo.com/2d987777c1a091339801114bb69ca30b.jpg

Here are the docs for the ConversionAction Object structure:
* https://opteo.com/dev/google-ads-api/#conversionaction
* https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v3.resources#google.ads.googleads.v3.resources.ConversionAction

Here are the docs for this create ConversionAction API:
* https://opteo.com/dev/google-ads-api/#create-conversionaction
* https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v3.services#conversionactionservice

I have tried every combination I could think of but even with all fields uncommented it shows this issue. 

Examples: 
With all fields uncommented, I get this same error.
With all fields uncommented except `Immutable` ones, I get this same error. 
With all fields uncommented except `Immutable` and `id`, I get this same error. 
With all fields uncommented except `Immutable` and `owner_customer`, I get this same error.
With all fields uncommented except `Immutable` and `owner_customer`, I get this same error. 
and many more combos... 

### Other information

```
//google-apis-test.js

const { GoogleAdsApi } = require('google-ads-api');

const client = new GoogleAdsApi({
    client_id: 'client_id',
    client_secret: 'client_secret',
    developer_token: 'developer_token',
});

const customer = client.Customer({
    customer_account_id: 'ADWORDS-ACCOUNT-ID',
    login_customer_id: 'MANAGER-ACCOUNT-ID', // Optionally provide a login-customer-id
    refresh_token: 'TOKEN',
});

// Error: The required field was not present.
const conversion_action = {
    //resource_name: '', //Immutable
    //id: 420420420, //Output only
    attribution_model_settings: {
        attribution_model: 101//,
        //data_driven_model_status: 5 //Output only
    },
    category: 4,
    click_through_lookback_window_days: 30,
    counting_type: 3,
    include_in_conversions_metric: true,
    name: 'My API Created conversion action',
    //owner_customer: 'customers/9105817791', //Output only
    phone_call_duration_seconds: 60,
    status: 2,
    //type: 0, //Immutable
    value_settings: {
        always_use_default_value: false,
        default_currency_code: 'USD',
        default_value: 1
    },
    view_through_lookback_window_days: 1,
    //tag_snippets: [], //Output only
    app_id: ''
  };
  
// Passing in a single entity to create
const conversionActionResult = customer.conversionActions.create(conversion_action);

setTimeout(async () => {
    console.log(await conversionActionResult);
}, 5000);
```

```
Sotacan-MBP:google-api-tests sotacan$ node google-apis-test.js
(node:40797) UnhandledPromiseRejectionWarning: Error: The required field was not present.
    at ConversionActionService.<anonymous> (/Users/sotacan/Documents/Projects/contract-work/Google-Tracker-Shopify-App/google-api-tests/node_modules/google-ads-api/build/services/service.js:199:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/sotacan/Documents/Projects/contract-work/Google-Tracker-Shopify-App/google-api-tests/node_modules/google-ads-api/build/services/service.js:6:65)
(node:40797) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:40797) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:40797) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(node:40797) UnhandledPromiseRejectionWarning: Error: The required field was not present.
    at ConversionActionService.<anonymous> (/Users/sotacan/Documents/Projects/contract-work/Google-Tracker-Shopify-App/google-api-tests/node_modules/google-ads-api/build/services/service.js:199:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/sotacan/Documents/Projects/contract-work/Google-Tracker-Shopify-App/google-api-tests/node_modules/google-ads-api/build/services/service.js:6:65)
(node:40797) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Sotacan-MBP:google-api-tests sotacan$ 
```

**Comment by kritzware** [comment]
See: https://github.com/Opteo/google-ads-node/issues/40#issuecomment-623780543

**Comment by kritzware** [comment]
Solution: https://github.com/Opteo/google-ads-node/issues/40#issuecomment-624120644
