### ISSUE TITLE
Invalid request problem

### ISSUE THREAD

**Issue by vitorfhc** [Opteo/google-ads-api#208]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [x] question about how to use this project

### Summary

I am receiving this error:

```
Error: 16 UNAUTHENTICATED: Failed to retrieve auth metadata with error: invalid_request
    at Object.callErrorFromStatus (/server/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/server/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/server/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/server/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /server/node_modules/@grpc/grpc-js/build/src/call-stream.js:130:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 16,
  details: 'Failed to retrieve auth metadata with error: invalid_request',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

Which I have no idea why it is happening. I checked the credentials ten times already.

Here is the code I am using:

```
import { GoogleAdsApi } from 'google-ads-api'

const credentials = {
    client_id: 'xxxxx-xxxxx.apps.googleusercontent.com',
    client_secret: 'xxxxx-xx',
    refresh_token: 'xxxxxx',
    developer_token: 'xxxxxx'
}

const client = new GoogleAdsApi(credentials)
client.listAccessibleCustomers(credentials)
.then(response => {
    console.log(response)
})
.catch(err => console.log(err))
```

### Other information

`node v14.15.4`
`"google-ads-api": "^4.0.4-beta.10"`
The Google Ads account has a normal account, a manager account and a manager test account
I used https://refresh-token-helper.opteo.com/ and my own website to try the authentication, neither worked

**Comment by MrNghia123** [comment]
Have the same problem when upgraded from v 4.0.3 to 5.1.3
