### ISSUE TITLE
GrpcError:  Version v3 is deprecated. Requests to this version will be blocked.

### ISSUE THREAD

**Issue by markhilton** [Opteo/google-ads-api#245]
```
GrpcError:  Version v3 is deprecated. Requests to this version will be blocked.
    at CustomerService.<anonymous> (/src/node_modules/google-ads-api/build/services/service.js:323:23)
    at Generator.throw (<anonymous>)
    at rejected (/src/node_modules/google-ads-api/build/services/service.js:6:65) {
  code: { requestError: 1 },
  request: {
    customerId: 'XXXXXXXXXX',
    query: 'SELECT campaign.id, campaign.name, metric.impressions, metrics.clicks FROM campaign WHERE campaign.status = "ENABLED" LIMIT 20',
    pageToken: '',
    pageSize: 10000,
    validateOnly: false,
    returnTotalResultsCount: false,
    summaryRowSetting: 2
  },
  failure: Error: 3 INVALID_ARGUMENT:  Version v3 is deprecated. Requests to this version will be blocked.
      at Object.exports.createStatusError (/src/node_modules/grpc/src/common.js:91:15)
      at Object.onReceiveStatus (/src/node_modules/grpc/src/client_interceptors.js:1209:28)
      at InterceptingListener._callNext (/src/node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.onReceiveStatus (/src/node_modules/grpc/src/client_interceptors.js:618:8)
      at Object.onReceiveStatus (/src/node_modules/google-ads-node/build/lib/interceptor.js:109:17)
      at InterceptingListener._callNext (/src/node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.onReceiveStatus (/src/node_modules/grpc/src/client_interceptors.js:618:8)
      at Object.onReceiveStatus (/src/node_modules/google-ads-node/build/lib/interceptor.js:161:13)
      at InterceptingListener._callNext (/src/node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.onReceiveStatus (/src/node_modules/grpc/src/client_interceptors.js:618:8)
      at callback (/src/node_modules/grpc/src/client_interceptors.js:847:24) {
    code: 3,
    metadata: Metadata { _internal_repr: [Object], flags: 0 },
    details: 'Version v3 is deprecated. Requests to this version will be blocked.'
  }
}
```

**Comment by markhilton** [comment]
Removing `node_modules/`, `package-lock.js` and re-installing packages seems to resolve the problem for me.
