### ISSUE TITLE
Creating campaignCriteria fails with 'TypeError: entities.map is not a function'

### ISSUE THREAD

**Issue by Gw1p** [Opteo/google-ads-api#249]
Type: BUG

Version: 5.1.1

Steps to reproduce:

```
const googleAdsApi = require('google-ads-api');
const googleAdsApiObj = new googleAdsApi.GoogleAdsApi({
  client_id: <client_id>,
  client_secret: <client_secret>,
  developer_token: <dev_token>,
});
const customer = googleAdsApiObj.Customer({customer_id: <customer_id>, login_customer_id: <login_customer_id>, refresh_token: <refresh_token>});
const newCampaignCriteria = { campaign: <campaign_ref> gender: {type: 10}, negative: true};
customer["campaignCriteria"].create(newCampaignCriteria);
```

This produces the following error:
```
Promise {
  <rejected> TypeError: entities.map is not a function
      at Customer.Service.buildOperations (C:\Users\anton\React\advertize\advertize-api\node_modules\google-ads-api\build\src\service.js:140:28)
      at Customer.<anonymous> (C:\Users\anton\React\advertize\advertize-api\node_modules\google-ads-api\build\src\protos\autogen\serviceFactory.js:4682:44)
      at step (C:\Users\anton\React\advertize\advertize-api\node_modules\google-ads-api\build\src\protos\autogen\serviceFactory.js:58:23)
      at Object.next (C:\Users\anton\React\advertize\advertize-api\node_modules\google-ads-api\build\src\protos\autogen\serviceFactory.js:39:53)
      at C:\Users\anton\React\advertize\advertize-api\node_modules\google-ads-api\build\src\protos\autogen\serviceFactory.js:33:71
      at new Promise (<anonymous>)
      at __awaiter (C:\Users\anton\React\advertize\advertize-api\node_modules\google-ads-api\build\src\protos\autogen\serviceFactory.js:29:12)
      at Object.create (C:\Users\anton\React\advertize\advertize-api\node_modules\google-ads-api\build\src\protos\autogen\serviceFactory.js:4677:71)
      at REPL12:1:30
      at Script.runInThisContext (node:vm:131:12)
}
> Uncaught TypeError: entities.map is not a function
    at Customer.Service.buildOperations (C:\Users\anton\React\advertize\advertize-api\node_modules\google-ads-api\build\src\service.js:140:28)
    at Customer.<anonymous> (C:\Users\anton\React\advertize\advertize-api\node_modules\google-ads-api\build\src\protos\autogen\serviceFactory.js:4682:44)
    at step (C:\Users\anton\React\advertize\advertize-api\node_modules\google-ads-api\build\src\protos\autogen\serviceFactory.js:58:23)
    at Object.next (C:\Users\anton\React\advertize\advertize-api\node_modules\google-ads-api\build\src\protos\autogen\serviceFactory.js:39:53)
    at C:\Users\anton\React\advertize\advertize-api\node_modules\google-ads-api\build\src\protos\autogen\serviceFactory.js:33:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\anton\React\advertize\advertize-api\node_modules\google-ads-api\build\src\protos\autogen\serviceFactory.js:29:12)
    at Object.create (C:\Users\anton\React\advertize\advertize-api\node_modules\google-ads-api\build\src\protos\autogen\serviceFactory.js:4677:71)
    at REPL12:1:30
    at Script.runInThisContext (node:vm:131:12)
```

This used to work fine on the version < 5, I think this should still work or at least handle it gracefully without crashing... or at least crash with a useful message.

**Comment by WillCooter** [comment]
Hi @Gw1p. In the latest version of the api the `create` function takes an array of mutations. See [here](https://github.com/Opteo/google-ads-api#create-an-expanded-text-ad) for an example.

**Comment by Gw1p** [comment]
All right, thank you!
