### ISSUE TITLE
Error: no such type: google.ads.googleads.v8.errors.GoogleAdsFailure

### ISSUE THREAD

**Issue by MitulGedeeya** [Opteo/google-ads-api#308]
While updating the campaign budget it throws following error.

```
Error: no such type: google.ads.googleads.v8.errors.GoogleAdsFailure
    at Root.lookupType (/mnt/Work/upwork/Genie Words/geniewords-api/node_modules/protobufjs/src/namespace.js:383:15)
    at GoogleErrorDecoder.decodeProtobufAny (/mnt/Work/upwork/Genie Words/geniewords-api/node_modules/google-gax/build/src/googleError.js:38:32)
    at /mnt/Work/upwork/Genie Words/geniewords-api/node_modules/google-gax/build/src/googleError.js:74:82
    at Array.map (<anonymous>)
    at /mnt/Work/upwork/Genie Words/geniewords-api/node_modules/google-gax/build/src/googleError.js:74:63
    at Array.forEach (<anonymous>)
    at GoogleErrorDecoder.decodeRpcStatusDetails (/mnt/Work/upwork/Genie Words/geniewords-api/node_modules/google-gax/build/src/googleError.js:71:19)
    at Immediate.callback (/mnt/Work/upwork/Genie Words/geniewords-api/node_modules/google-gax/build/src/call.js:89:49)
    at processImmediate (internal/timers.js:463:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by MitulGedeeya** [comment]
It crashes the server

**Comment by kritzware** [comment]
I'll close this issue as the other one has more information in it: https://github.com/Opteo/google-ads-api/issues/309
