### ISSUE TITLE
GRPC error

### ISSUE THREAD

**Issue by dlseanan** [Opteo/google-ads-api#446]
Hi Opteo,

I keep getting the following error bo matter what method i call:

```
Error: 12 UNIMPLEMENTED: GRPC target method can't be resolved.
     at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/src/call.ts:81:24)
     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client.ts:351:36)
     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:462:34)
     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
     at /app/node_modules/@grpc/grpc-js/src/call-stream.ts:330:24
     at processTicksAndRejections (node:internal/process/task_queues:76:11) {
   code: 12,
   details: "GRPC target method can't be resolved.",
   metadata: Metadata { internalRepr: Map(0) {}, options: {} },
   note: 'Exception occurred in retry method that was not classified as transient'
}
```

Initially is was on the `customer.report()` functions, but i checked `client.listAccessibleCustomers` and it happens there too.
Sending axios requests with the same credentials works fine.
First thought it was an API version issue, but sunsetting of v11 is not until the end of March.

Please help

**Comment by wcoots** [comment]
Hi @dlseanan, this is very little information to go on. Could you provide more details please?
