### ISSUE TITLE
Error: Parser cannot parse input: expected a value

### ISSUE THREAD

**Issue by simplenotezy** [Opteo/google-ads-api#500]
With the following code:

```ts
    const customers = await client.listAccessibleCustomers(credentials.key);

    for (const customerId of customers.resource_names) {
      // Also supports login & linked customer ids
      const customer = client.Customer({
        customer_id: customerId,
        refresh_token: credentials.key,
      });

      try {
        const campaigns = await customer.report({
          entity: 'campaign',
          attributes: [
            'campaign.id',
            'campaign.name',
            'campaign.bidding_strategy_type',
            'campaign_budget.amount_micros',
          ],
          metrics: [
            'metrics.cost_micros',
            'metrics.clicks',
            'metrics.impressions',
            'metrics.all_conversions',
          ],
          constraints: {
            'campaign.status': enums.CampaignStatus.ENABLED,
          },
          limit: 20,
        });

        console.log(campaigns);
      } catch (error) {
        console.error(error);
      }
    }
```

I am getting this error:

```
Error: Parser cannot parse input: expected a value
    at Parser._processBuffer (/Users/mf/Projects/kite/backend/node_modules/.pnpm/stream-json@1.8.0/node_modules/stream-json/Parser.js:111:64)
    at Parser._transformBuffer (/Users/mf/Projects/kite/backend/node_modules/.pnpm/stream-json@1.8.0/node_modules/stream-json/utils/Utf8Stream.js:24:10)
    at Parser._transform (/Users/mf/Projects/kite/backend/node_modules/.pnpm/stream-json@1.8.0/node_modules/stream-json/utils/Utf8Stream.js:19:10)
    at Parser.Transform._write (node:internal/streams/transform:171:8)
    at writeOrBuffer (node:internal/streams/writable:564:12)
    at _write (node:internal/streams/writable:493:10)
    at Parser.Writable.write (node:internal/streams/writable:502:10)
    at IncomingMessage.ondata (node:internal/streams/readable:1007:22)
    at IncomingMessage.emit (node:events:518:28)
    at IncomingMessage.emit (node:domain:488:12) {stack: 'Error: Parser cannot parse input: expected a … at IncomingMessage.emit (node:domain:488:12)', message: 'Parser cannot parse input: expected a value'}
```

**Comment by visrut-at-handldigital** [comment]
Thanks, @simplenotezy, for the solution you found. Yes, the error is not handled properly after console logging inside `node_modules`. I got to know something was **404** but didn't know the reason. After your suggestion, the below code worked for me.

```js
const client = new GoogleAdsApi({
  client_id: process.env.GOOGLE_ADWORDS_CLIENT_ID!,
  client_secret: process.env.GOOGLE_ADWORDS_CLIENT_SECRET!,
  developer_token: process.env.GOOGLE_ADWORDS_DEVELOPER_TOKEN!,
});

const customerIds = (await client.listAccessibleCustomers(refreshToken)).resource_names;

const customer = client.Customer({
  customer_id: customerIds[0].replace('customers/', ''),
  refresh_token: refreshToken,
});
```

A good error message would help since I overlooked the docs and don't seem to notice that we only need to pass the ID, not the `customers/` prefix.
