### ISSUE TITLE
Can't create a Campaign

### ISSUE THREAD

**Issue by aminasyaEpam** [Opteo/google-ads-api#93]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   question about how to use this project

### Summary

I can't create a campaign. Looks like it requires a bidding strategy that I have no idea how to pass.
I am able to authenticate with my Google Ads account. Now I use this code to add a Campaign.
```
const campaign = {
    name: 'New Campaign',
    campaign_budget: 'customers/2044536946/campaignBudgets/6627694987',
    advertising_channel_type: enums.AdvertisingChannelType.SEARCH,
    status: enums.CampaignStatus.PAUSED,
}

customer.campaigns.create(campaign).then(res => {
    console.log(res);
}).catch( error => {
    console.log(error);
})
```

It prints following error:
```
PS C:\Users\Ashot_Minasyan\Desktop\adwords> ts-node app.ts
{ Error: The required field was not present.
    at CampaignService.<anonymous> (C:\Users\Ashot_Minasyan\Desktop\adwords\node_modules\google-ads-api\build\services\service.js:178:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Ashot_Minasyan\Desktop\adwords\node_modules\google-ads-api\build\services\service.js:6:65)
  code: { fieldError: 2 },
  request:
   { customerId: '2044536946',
     operationsList: [ [Object] ],
     partialFailure: false,
     validateOnly: false },
  request_id: 'sAAlZWQczDFJSNHEn4iMqw',
  location: 'operations[0].create.campaign_bidding_strategy',
  failure:
   { Error: 3 INVALID_ARGUMENT: The required field was not present.
       at Object.exports.createStatusError (C:\Users\Ashot_Minasyan\Desktop\adwords\node_modules\grpc\src\common.js:91:15)
       at Object.onReceiveStatus (C:\Users\Ashot_Minasyan\Desktop\adwords\node_modules\grpc\src\client_interceptors.js:1209:28)
       at InterceptingListener._callNext (C:\Users\Ashot_Minasyan\Desktop\adwords\node_modules\grpc\src\client_interceptors.js:568:42)
       at InterceptingListener.onReceiveStatus (C:\Users\Ashot_Minasyan\Desktop\adwords\node_modules\grpc\src\client_interceptors.js:618:8)
       at Object.grpc_1.default.ListenerBuilder.withOnReceiveStatus [as onReceiveStatus] (C:\Users\Ashot_Minasyan\Desktop\adwords\node_modules\google-ads-node\src\lib\interceptor.ts:96:11)
       at InterceptingListener._callNext (C:\Users\Ashot_Minasyan\Desktop\adwords\node_modules\grpc\src\client_interceptors.js:568:42)
       at InterceptingListener.onReceiveStatus (C:\Users\Ashot_Minasyan\Desktop\adwords\node_modules\grpc\src\client_interceptors.js:618:8)
       at Object.grpc_1.default.ListenerBuilder.withOnReceiveStatus [as onReceiveStatus] (C:\Users\Ashot_Minasyan\Desktop\adwords\node_modules\google-ads-node\src\lib\interceptor.ts:198:9)
       at InterceptingListener._callNext (C:\Users\Ashot_Minasyan\Desktop\adwords\node_modules\grpc\src\client_interceptors.js:568:42)
       at InterceptingListener.onReceiveStatus (C:\Users\Ashot_Minasyan\Desktop\adwords\node_modules\grpc\src\client_interceptors.js:618:8)
     code: 3,
     metadata: Metadata { _internal_repr: [Object], flags: 0 },
     details: 'The required field was not present.' } }
```

**Comment by Riley-Blair** [comment]
A bidding strategy must be provided when creating a campaign (see: `location: 'operations[0].create.campaign_bidding_strategy',` in the error response).

From the official Google Ads API documentation: "Union field campaign_bidding_strategy. The bidding strategy for the campaign. Must be either portfolio (created via BiddingStrategy service) or standard, that is embedded into the campaign. campaign_bidding_strategy can be only one of the following..."

To create your campaign, you'll need to specify the bidding strategy to be used by the campaign using one of the appropriate strategy properties (see: https://opteo.com/dev/google-ads-api/#campaign).

**Comment by noudadrichem** [comment]
While creating bidding_strategies it's giving a `required field is not present` on `scheme`. I can't find anything related to `scheme` on the `bidding_strategy` object. How does this work?

**Comment by kritzware** [comment]
Did you manage to resolve this issue @aminasyaEpam ?

Hi @noudadrichem, could you please provide a code example of the error you're facing? Even better, make a new issue if it's unrelated to this 👍

**Comment by sogangCSmaster** [comment]
I am facing the same problem.
After making campain_budget id, I copied the exact same code in README
`const campaign = {
    name: 'New Campaign',
    campaign_budget: 'customers/123/campaignBudgets/123',
    advertising_channel_type: enums.AdvertisingChannelType.SEARCH,
    status: enums.CampaignStatus.PAUSED,
}
const { results } = await customer.campaigns.create(campaign);
`

**Comment by Eslam3bed** [comment]
@Riley-Blair 
I managed to create a Bidding Strategy with the following sample:

```js
const bidding_strategy = {
    name: `Sample-Bidding-Strategy`,
    status: enums.BiddingStrategyStatus.UNSPECIFIED,
    type: enums.BiddingStrategyType.MANUAL_CPM,
    target_spend: {
        target_spend_micros: 2000000,
        cpc_bid_ceiling_micros: 1000000
    }
}
const {
 results: [ biddingStrategyResourceName] = [] 
   } = await customer.biddingStrategies.create(bidding_strategy)
```
