### ISSUE TITLE
Its seems like some bugs in library while creating "responsive_display_ad" 

### ISSUE THREAD

**Issue by umar0107** [Opteo/google-ads-api#95]
### I'm submitting a 
-   [+] bug report

Its seems like some bugs in library while creating "responsive_display_ad" 

`TypeError: valueType.startsWith is not a function
    at toProtoValueFormat (C:\Users\Rabshan\Desktop\nodeJS-projects\realreach-backend\node_modules\google-ads-node\build\lib\utils.js:101:19)
    at unroll (C:\Users\Rabshan\Desktop\nodeJS-projects\realreach-backend\node_modules\google-ads-node\build\lib\utils.js:89:19)
    at pb.(anonymous function).value.map (C:\Users\Rabshan\Desktop\nodeJS-projects\realreach-backend\node_modules\google-ads-node\build\lib\utils.js:81:24)
    at Array.map (<anonymous>)
    at convertToProtoFormat (C:\Users\Rabshan\Desktop\nodeJS-projects\realreach-backend\node_modules\google-ads-node\build\lib\utils.js:80:36)
    at unroll (C:\Users\Rabshan\Desktop\nodeJS-projects\realreach-backend\node_modules\google-ads-node\build\lib\utils.js:88:19)
    at convertToProtoFormat (C:\Users\Rabshan\Desktop\nodeJS-projects\realreach-backend\node_modules\google-ads-node\build\lib\utils.js:85:26)
    at unroll (C:\Users\Rabshan\Desktop\nodeJS-projects\realreach-backend\node_modules\google-ads-node\build\lib\utils.js:88:19)
    at Object.convertToProtoFormat (C:\Users\Rabshan\Desktop\nodeJS-projects\realreach-backend\node_modules\google-ads-node\build\lib\utils.js:85:26)     
    at GoogleAdsClient.buildResource (C:\Users\Rabshan\Desktop\nodeJS-projects\realreach-backend\node_modules\google-ads-node\build\lib\client.js:82:41)  
    at GrpcClient.buildResource (C:\Users\Rabshan\Desktop\nodeJS-projects\realreach-backend\node_modules\google-ads-api\build\grpc.js:106:28)
    at AdGroupAdService.buildResource (C:\Users\Rabshan\Desktop\nodeJS-projects\realreach-backend\node_modules\google-ads-api\build\services\service.js:190:32)
    at AdGroupAdService.<anonymous> (C:\Users\Rabshan\Desktop\nodeJS-projects\realreach-backend\node_modules\google-ads-api\build\services\service.js:90:33)
    at Generator.next (<anonymous>)
    at C:\Users\Rabshan\Desktop\nodeJS-projects\realreach-backend\node_modules\google-ads-api\build\services\service.js:8:71`

then i make some changes this in util.js file line 100
use this
`if (typeof valueType !== "object" && valueType.startsWith("enum_")) {
        return value;
}`
instead of this
`if (valueType.startsWith("enum_")) {
        return value;
}`
and that error solved but after that got error of 'The required field was not present' (headlines and descriptions) even i'm adding these field correctly like below
`const adParams = {
            ad_group: adGroup.resourceName,
            status: enums.AdGroupAdStatus.PAUSED,
            ad: {
                final_urls: [param.finalUrl],
                name: param.heading1,
                // type: enums.ServedAssetFieldType.HEADLINE_1,
                // display_url: param.finalUrl,
                responsive_display_ad: {
                    business_name: 'ABC',
                    descriptions: ['des1', 'des2'],
                    headlines: ['head1', 'head2'],
                    logo_images: [imageBase641],
                    marketing_images: [imageBase642],
                    square_logo_images: [imageBase643],
                    square_marketing_images: [imageBase644],
                    long_headline: {
                        pinned_field: enums.ServedAssetFieldType.HEADLINE_1,
                        text: 'head1'
                    },
                }
            }
        }
const { results } = await customer.adGroupAds.create(adParams)`

Please have look on these issue and let me know if i'm doing anything wrong.
Thanks in advance.

**Comment by umar0107** [comment]
Hi @avermeil ,
Please let me know about solution of this issue, i'm very time pressed.
Thanks

**Comment by avermeil** [comment]
Hey @umar0107  -- sorry about taking so long.

This was an error in the documentation rather than the library itself. Fields like `descriptions` are actually arrays of `objects`, not `strings`. 

For example, this would be the correct way to specify `descriptions` and `logo_images` when creating a responsive display ad:

```javascript
const adParams = {
    ad: {
        responsive_display_ad: {
            descriptions: [
                { text: 'desc1', pinned_field: enums.ServedAssetFieldType.UNSPECIFIED },
            ],
            logo_images: [{ asset: img }],
        },
    },
}
const results = await customer.adGroupAds.create(adParams)
```

Hope this helps!

**Comment by avermeil** [comment]
Closing this for now. Feel free to reopen if anything else comes up!
